# Generated by Django 4.2.20 on 2025-05-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mynews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reads",
            options={"managed": True},
        ),
    ]
