# Generated by Django 4.2.20 on 2025-05-09 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mynews", "0002_alter_reads_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reads",
            name="read_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
