# Generated by Django 4.2.20 on 2025-05-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_reads_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
