# Generated by Django 4.2.20 on 2025-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0004_alter_news_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
